microservice:
    payment-service:
      endpoints:
         endpoint:
            uri: http://PAYMENT-SERVICE/payment/doPaymentProc
    order-service:
      endpoints:
         endpoint:
            uri: http://ORDER-SERVICE/order/bookOrder      
      
      
      
